import os
import pyautogui
print("Create a Database Backup directory called SMP")

path="E:/SMP"
if not os.path.exists(path):
    os.makedirs(path)
pyautogui.click(603,1046)
print("Select the SalesMate + Application")
pyautogui.typewrite("salesMate +")
print("Press Enter Key again to close the Tip Of the Day Dialog")
pyautogui.press("enter",1,5)
print(" alt and f shortcut key to invoke the File Root menu")
print("Now press 'b' to invoke the Bacuup Folder Dialog")
pyautogui.press(['alt','f'])
pyautogui.press("b")
print("Go to E Drive")
print("Now press Right arrow Key to Expand the Tree")
pyautogui.press("l",1,1)
pyautogui.press("right",1,1)
print("Go to SMP Folder")
pyautogui.typewrite("smp")
print("Press Enter Key to Backup Data")

print("Press Enter to Close the OK Button")
pyautogui.press("enter",1,2)
pyautogui.press("enter",1,1)
#Adding a new customer details
pyautogui.press(['alt','c'])
print("add a new customer detail")
pyautogui.press("enter",1,1)
pyautogui.typewrite("5677")
pyautogui.press("enter",1,1)
pyautogui.press("enter",1,1)
pyautogui.typewrite("Raj")
pyautogui.press("enter",1,1)
pyautogui.typewrite("kumar")
pyautogui.press("enter",1,1)
pyautogui.typewrite("Mr")
pyautogui.press("enter",1,1)
pyautogui.typewrite("palai kottayam")
pyautogui.press("enter",1,1)
pyautogui.typewrite("9865741258")
pyautogui.press("enter",1,1)
pyautogui.typewrite("rajkumar@gmail.com")
pyautogui.press("enter",1,1)
pyautogui.press("down",1,1)
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("enter")
pyautogui.press("enter",1,2)
print("opening new checkout")
pyautogui.press("f6",1,1)
print("add a new stock item detail")
pyautogui.press(['alt','s'])
pyautogui.press("n")

pyautogui.press("enter",1,1)
pyautogui.typewrite("7788")
pyautogui.press("enter",1,1)
pyautogui.typewrite("eastern")
pyautogui.press("enter",1,1)
pyautogui.press("down",1,1)
pyautogui.press("enter",1,1)
pyautogui.typewrite("10")
pyautogui.press("enter",1,1)
pyautogui.typewrite("newworld")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("space",1,1)
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.typewrite("579")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("enter",1,1)
pyautogui.press("enter",1,1)
print("close the stock detail menu")
pyautogui.hotkey('esc')
print("closing the salesmate+")
pyautogui.keyDown('alt')
pyautogui.keyDown('f4')